import CardImage from '@/assets/event_card_image.png'
export const EventCardList = [
    {
        date:"10th December 2022",
        image: CardImage,
        main_heading:"Sample main heading",
        subHeading:"Sample sub heading",
        ticketPrice: "$15",
        age:"All Ages",
        eventStatus:{
            isSoldOut:true,
            isCancelled:false,
            isPrivate:false,
        },
    },
    {
        date:"10th December 2022",
        image: CardImage,
        main_heading:"Sample main heading",
        subHeading:"Sample sub heading",
        ticketPrice: "$15",
        age:"All Ages",
        eventStatus:{
            isSoldOut:true,
            isCancelled:false,
            isPrivate:false,
        },
    },
    {
        date:"10th December 2022",
        image: CardImage,
        main_heading:"Sample main heading",
        subHeading:"Sample sub heading",
        ticketPrice: "$15",
        age:"All Ages",
        eventStatus:{
            isSoldOut:false,
            isCancelled:true,
            isPrivate:false,
        },
    },
    {
        date:"10th December 2022",
        image: CardImage,
        main_heading:"Sample main heading",
        subHeading:"Sample sub heading",
        ticketPrice: "$15",
        age:"All Ages",
        eventStatus:{
            isSoldOut:false,
            isCancelled:false,
            isPrivate:true,
        },
    },
    {
        date:"10th December 2022",
        image: CardImage,
        main_heading:"Sample main heading",
        subHeading:"Sample sub heading",
        ticketPrice: "$15",
        age:"All Ages",
        eventStatus:{
            isSoldOut:true,
            isCancelled:false,
            isPrivate:false,
        },
    },
   
    {
        date:"10th December 2022",
        image: CardImage,
        main_heading:"Sample main heading",
        subHeading:"Sample sub heading",
        ticketPrice: "$15",
        age:"All Ages",
        eventStatus:{
            isSoldOut:false,
            isCancelled:false,
            isPrivate:true,
        },
    },
    {
        date:"10th December 2022",
        image: CardImage,
        main_heading:"Sample main heading",
        subHeading:"Sample sub heading",
        ticketPrice: "$15",
        age:"All Ages",
        eventStatus:{
            isSoldOut:false,
            isCancelled:true,
            isPrivate:false,
        },
    },
    {
        date:"10th December 2022",
        image: CardImage,
        main_heading:"Sample main heading",
        subHeading:"Sample sub heading",
        ticketPrice: "$15",
        age:"All Ages",
        eventStatus:{
            isSoldOut:false,
            isCancelled:false,
            isPrivate:true,
        },
    },
    {
        date:"10th December 2022",
        image: CardImage,
        main_heading:"Sample main heading",
        subHeading:"Sample sub heading",
        ticketPrice: "$15",
        age:"All Ages",
        eventStatus:{
            isSoldOut:true,
            isCancelled:false,
            isPrivate:false,
        },
    },
    {
        date:"10th December 2022",
        image: CardImage,
        main_heading:"Sample main heading",
        subHeading:"Sample sub heading",
        ticketPrice: "$15",
        age:"All Ages",
        eventStatus:{
            isSoldOut:true,
            isCancelled:false,
            isPrivate:false,
        },
    },
    {
        date:"10th December 2022",
        image: CardImage,
        main_heading:"Sample main heading",
        subHeading:"Sample sub heading",
        ticketPrice: "$15",
        age:"All Ages",
        eventStatus:{
            isSoldOut:true,
            isCancelled:false,
            isPrivate:false,
        },
    },
    {
        date:"10th December 2022",
        image: CardImage,
        main_heading:"Sample main heading",
        subHeading:"Sample sub heading",
        ticketPrice: "$15",
        age:"All Ages",
        eventStatus:{
            isSoldOut:false,
            isCancelled:true,
            isPrivate:false,
        },
    },
    {
        date:"10th December 2022",
        image: CardImage,
        main_heading:"Sample main heading",
        subHeading:"Sample sub heading",
        ticketPrice: "$15",
        age:"All Ages",
        eventStatus:{
            isSoldOut:false,
            isCancelled:false,
            isPrivate:true,
        },
    },
    {
        date:"10th December 2022",
        image: CardImage,
        main_heading:"Sample main heading",
        subHeading:"Sample sub heading",
        ticketPrice: "$15",
        age:"All Ages",
        eventStatus:{
            isSoldOut:true,
            isCancelled:false,
            isPrivate:false,
        },
    },
   
    {
        date:"10th December 2022",
        image: CardImage,
        main_heading:"Sample main heading",
        subHeading:"Sample sub heading",
        ticketPrice: "$15",
        age:"All Ages",
        eventStatus:{
            isSoldOut:false,
            isCancelled:false,
            isPrivate:true,
        },
    },
    {
        date:"10th December 2022",
        image: CardImage,
        main_heading:"Sample main heading",
        subHeading:"Sample sub heading",
        ticketPrice: "$15",
        age:"All Ages",
        eventStatus:{
            isSoldOut:false,
            isCancelled:true,
            isPrivate:false,
        },
    },
    {
        date:"10th December 2022",
        image: CardImage,
        main_heading:"Sample main heading",
        subHeading:"Sample sub heading",
        ticketPrice: "$15",
        age:"All Ages",
        eventStatus:{
            isSoldOut:false,
            isCancelled:false,
            isPrivate:true,
        },
    },
    {
        date:"10th December 2022",
        image: CardImage,
        main_heading:"Sample main heading",
        subHeading:"Sample sub heading",
        ticketPrice: "$15",
        age:"All Ages",
        eventStatus:{
            isSoldOut:true,
            isCancelled:false,
            isPrivate:false,
        },
    },
    {
        date:"10th December 2022",
        image: CardImage,
        main_heading:"Sample main heading",
        subHeading:"Sample sub heading",
        ticketPrice: "$15",
        age:"All Ages",
        eventStatus:{
            isSoldOut:true,
            isCancelled:false,
            isPrivate:false,
        },
    },
    {
        date:"10th December 2022",
        image: CardImage,
        main_heading:"Sample main heading",
        subHeading:"Sample sub heading",
        ticketPrice: "$15",
        age:"All Ages",
        eventStatus:{
            isSoldOut:true,
            isCancelled:false,
            isPrivate:false,
        },
    },
    {
        date:"10th December 2022",
        image: CardImage,
        main_heading:"Sample main heading",
        subHeading:"Sample sub heading",
        ticketPrice: "$15",
        age:"All Ages",
        eventStatus:{
            isSoldOut:false,
            isCancelled:true,
            isPrivate:false,
        },
    },
    {
        date:"10th December 2022",
        image: CardImage,
        main_heading:"Sample main heading",
        subHeading:"Sample sub heading",
        ticketPrice: "$15",
        age:"All Ages",
        eventStatus:{
            isSoldOut:false,
            isCancelled:false,
            isPrivate:true,
        },
    },
    {
        date:"10th December 2022",
        image: CardImage,
        main_heading:"Sample main heading",
        subHeading:"Sample sub heading",
        ticketPrice: "$15",
        age:"All Ages",
        eventStatus:{
            isSoldOut:true,
            isCancelled:false,
            isPrivate:false,
        },
    },
   
    {
        date:"10th December 2022",
        image: CardImage,
        main_heading:"Sample main heading",
        subHeading:"Sample sub heading",
        ticketPrice: "$15",
        age:"All Ages",
        eventStatus:{
            isSoldOut:false,
            isCancelled:false,
            isPrivate:true,
        },
    },
    {
        date:"10th December 2022",
        image: CardImage,
        main_heading:"Sample main heading",
        subHeading:"Sample sub heading",
        ticketPrice: "$15",
        age:"All Ages",
        eventStatus:{
            isSoldOut:false,
            isCancelled:true,
            isPrivate:false,
        },
    },
    {
        date:"10th December 2022",
        image: CardImage,
        main_heading:"Sample main heading",
        subHeading:"Sample sub heading",
        ticketPrice: "$15",
        age:"All Ages",
        eventStatus:{
            isSoldOut:false,
            isCancelled:false,
            isPrivate:true,
        },
    },
    {
        date:"10th December 2022",
        image: CardImage,
        main_heading:"Sample main heading",
        subHeading:"Sample sub heading",
        ticketPrice: "$15",
        age:"All Ages",
        eventStatus:{
            isSoldOut:true,
            isCancelled:false,
            isPrivate:false,
        },
    },
    
]